### ISSUE TITLE
Undocumented error raised from `fetch_br_stats`

### ISSUE THREAD

**Issue by trevorflahardy** [Fortnite-API/py-wrapper#32]
### Summary

Attempting to fetch the stats of a player who has them private raises `Forbidden` but this it not documented.

### Reproduction Steps

Simply attempt to fetch the stats of a user who has them private.

### Minimal Reproducible Code

```python
async with fortnite_api.Client(api_key='...') as client:
    stats = await client.fetch_br_stats(account_id='1a46c68f24bb479eadb8f312a9af7f3e')
```

### Expected Results

A documented exception is to be raised so it can be handled.

### Actual Results

```python
chai_bot       | 2024-11-02 00:11:04 ERROR    utils.eh Unhandled exception
chai_bot       | Traceback (most recent call last):
chai_bot       |   File "/usr/local/lib/python3.12/site-packages/discord/app_commands/commands.py", line 857, in _do_call
chai_bot       |     return await self._callback(self.binding, interaction, **params)  # type: ignore
chai_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chai_bot       |   File "/src/cogs/auth/stats.py", line 70, in stats
chai_bot       |     stats = await self.bot.fortnite_api.fetch_br_stats(
chai_bot       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chai_bot       |   File "/usr/local/lib/python3.12/site-packages/fortnite_api/client.py", line 1048, in fetch_br_stats
chai_bot       |     data = await self.http.get_br_stats_by_id(
chai_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chai_bot       |   File "/usr/local/lib/python3.12/site-packages/fortnite_api/http.py", line 408, in request
chai_bot       |     raise Forbidden(error, response, data)
chai_bot       | fortnite_api.errors.Forbidden: the requested account's stats are not public
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my API key from display, if visible.

**Comment by Luc1412** [comment]
Solved by 04e4d3ccc461f3ac6b3d316ddf47480d44d9c00b
