### ISSUE TITLE
'shoe' is not a valid CosmeticType

### ISSUE THREAD

**Issue by Not-Bay** [Fortnite-API/py-wrapper#35]
### Summary

Iterating on `AsyncClient.fetch_cosmetics_br` results raises an exception

### Reproduction Steps

* Create an `fortnite_api.SyncClient`
* Fetch all cosmetics
* Iterate on cosmetics

### Minimal Reproducible Code

```python
import fortnite_api

with fortnite_api.SyncClient() as client:

    cosmetics = client.fetch_cosmetics_all()

    for cosmetic in cosmetics:
        pass

    print('Ok')
```

### Expected Results

Console prints `Ok`

### Actual Results

An error appears
```
Traceback (most recent call last):
  File "/app/test.py", line 7, in <module>
    for cosmetic in cosmetics:
                    ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/all.py", line 145, in __iter__
    for br in self.br:
              ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/proxies.py", line 142, in __iter__
    yield self._transform_at(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/proxies.py", line 65, in _transform_at
    result = self._transform_data(raw_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/all.py", line 105, in <lambda>
    lambda x: CosmeticBr(data=x, http=self._http),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/cosmetics/br.py", line 307, in __init__
    self.type: Optional[CosmeticTypeInfo[HTTPClientT]] = _type and CosmeticTypeInfo(data=_type, http=http)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fortnite_api/cosmetics/common.py", line 128, in __init__
    self.value: CosmeticType = CosmeticType(data["value"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'shoe' is not a valid CosmeticType
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my API key from display, if visible.

### Additional Context

I was originally using the async client and fetching br cosmetics only, the issue is basically the same

**Comment by Luc1412** [comment]
This has been fixed with 693ab9225eae460dc4c1cfb57fce58f67dec79de and is available in 3.2.0a. The final 3.2.0 release with this will be published today.
